apiVersion: v1
data:
  daemon.json: |-
    {
      "insecure-registries": ["registry.brmartin.co.uk:443"]
    }
immutable: false
kind: ConfigMap
metadata:
  labels:
    app: gitlab-runner
  name: gitlab-runner-docker-daemon
  namespace: ci
