apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: hestia-ci-store-gc
  name: hestia-ci-store-gc
  namespace: ci
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
