apiVersion: v1
data:
  config.js: |
    window.FEEDBACK_ADMIN_CONFIG = {
      authority: 'https://sso.brmartin.co.uk/realms/prod',
      clientId: 'feedback-admin',
      apiBase: 'https://feedback.brmartin.co.uk'
    };
kind: ConfigMap
metadata:
  labels:
    app: feedback-admin
  name: feedback-admin-config
  namespace: default
