apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-feedback-schema.yaml
- deployment-default-feedback-api.yaml
- ingress-default-feedback-api.yaml
- service-default-feedback-api.yaml

images:
- name: postgrest/postgrest
  newTag: v14.12
- name: postgres
  newTag: 18-alpine
