apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-overseerr-litestream.yaml
- deployment-default-overseerr.yaml
- ingress-default-overseerr.yaml
- persistentvolumeclaim-default-overseerr-config-sw.yaml
- service-default-overseerr.yaml
- verticalpodautoscaler-default-overseerr-vpa.yaml

images:
- name: "sctx/overseerr"
  newTag: "latest"
- name: "litestream/litestream"
  newTag: "0.5"
