apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-iris.yaml
- deployment-default-iris-valkey.yaml
- ingress-default-iris.yaml
- persistentvolume-iris-synology-media.yaml
- persistentvolumeclaim-default-iris-image-cache-windsor.yaml
- persistentvolumeclaim-default-iris-synology-media.yaml
- resourceclaim-default-iris-transcode.yaml
- service-default-iris.yaml
- service-default-iris-valkey.yaml

images:
- name: "registry.brmartin.co.uk/ben/iris"
  digest: "sha256:509f8bb5f6aa7496138dda0d6a7e5ef68e8665e5af34783e49414c24256a99bf"
- name: "valkey/valkey"
  newTag: "9-alpine"
