apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-iris.yaml
- deployment-default-iris-valkey.yaml
- ingress-default-iris.yaml
- persistentvolume-iris-synology-media.yaml
- persistentvolumeclaim-default-iris-image-cache-sw.yaml
- persistentvolumeclaim-default-iris-synology-media.yaml
- resourceclaim-default-iris-transcode.yaml
- service-default-iris.yaml
- service-default-iris-valkey.yaml

images:
- name: "registry.brmartin.co.uk/ben/iris"
  newTag: "latest"
- name: "valkey/valkey"
  newTag: "8-alpine"
