apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: iris
  name: iris-synology-media
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: synology-nfs-static
  volumeMode: Filesystem
