apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  finalizers:
  - resource.kubernetes.io/delete-protection
  name: iris-transcode
  namespace: default
spec:
  devices:
    requests:
    - exactly:
        allocationMode: ExactCount
        count: 1
        deviceClassName: iris-transcode-hw
      name: transcode
