apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-alloy.yaml
- clusterrolebinding-alloy.yaml
- configmap-default-alloy-config.yaml
- daemonset-default-alloy.yaml
- service-default-alloy.yaml
- serviceaccount-default-alloy.yaml

images:
- name: "grafana/alloy"
  newTag: "v1.16.1"
