apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  name: alloy
  namespace: default
