apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '12345'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  name: alloy
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 12345
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  sessionAffinity: None
  type: ClusterIP
