apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-rpi5-dra-driver.yaml
- clusterrolebinding-rpi5-dra-driver.yaml
- daemonset-kube-system-rpi5-dra-driver.yaml
- serviceaccount-kube-system-rpi5-dra-driver.yaml
