apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingressroute-default-seaweedfs-filer.yaml
- ingressroute-default-seaweedfs-master.yaml
- service-default-seaweedfs-filer-ui.yaml
- service-default-seaweedfs-master-ui.yaml
