apiVersion: v1
kind: Service
metadata:
  labels:
    app: seaweedfs
    component: master
    environment: prod
  name: seaweedfs-master-ui
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9333
    protocol: TCP
    targetPort: 9333
  selector:
    app: seaweedfs
    component: master
  sessionAffinity: None
  type: ClusterIP
