apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-jayne-martin-counselling.yaml
- ingress-default-jayne-martin-counselling.yaml
- service-default-jayne-martin-counselling.yaml
- verticalpodautoscaler-default-jayne-martin-counselling-vpa.yaml
