apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: jayne-martin-counselling
    environment: production
  name: jayne-martin-counselling-vpa
  namespace: default
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: jayne-martin-counselling
      maxAllowed:
        cpu: 200m
        memory: 128Mi
      minAllowed:
        cpu: 5m
        memory: 16Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jayne-martin-counselling
  updatePolicy:
    updateMode: 'Off'
