apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: nvidia-dra-driver-gpu
    meta.helm.sh/release-namespace: nvidia-dra-driver
  labels:
    app.kubernetes.io/instance: nvidia-dra-driver-gpu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-dra-driver-gpu
    app.kubernetes.io/version: 25.12.0
    helm.sh/chart: nvidia-dra-driver-gpu-25.12.0
  name: nvidia-dra-driver-gpu-service-account-controller
  namespace: nvidia-dra-driver
