apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: media-synology-docker
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Ti
  mountOptions:
  - soft
  - timeo=150
  - retrans=3
  nfs:
    path: /volume1/docker
    server: 192.168.1.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-nfs-static
  volumeMode: Filesystem
