apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: victoriametrics
    app.kubernetes.io/name: victoriametrics
  name: victoriametrics
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoriametrics
      app.kubernetes.io/name: victoriametrics
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/backup-script: 2670cf1911c7ce095762a15f6928aa1af4605ddd54e357b6782924997df6481f
        checksum/scrape-config: c7b417d659212330bc46640e59dc024b23aab3b1cf9b8f683f9490d612dda636
        prometheus.io/port: '8428'
        prometheus.io/scrape: 'true'
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/instance: victoriametrics
        app.kubernetes.io/name: victoriametrics
        app.kubernetes.io/version: v1.108.1
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - -storageDataPath=/victoria-metrics-data
        - -retentionPeriod=30d
        - -promscrape.config=/config/scrape.yml
        - -httpListenAddr=:8428
        - -selfScrapeInterval=15s
        image: victoriametrics/victoria-metrics
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: victoriametrics
        ports:
        - containerPort: 8428
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 900Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          mountPropagation: None
          name: config
          readOnly: true
        - mountPath: /victoria-metrics-data
          mountPropagation: None
          name: data
      - command:
        - /bin/sh
        - /scripts/backup.sh
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: MINIO_ACCESS_KEY
              name: victoriametrics-s3
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: MINIO_SECRET_KEY
              name: victoriametrics-s3
              optional: false
        image: victoriametrics/vmbackup
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - 'echo ''preStop: waiting for vmbackup-prod to finish''; while pidof
                vmbackup-prod >/dev/null 2>&1; do sleep 1; done; echo ''preStop: vmbackup
                idle, allowing termination'''
        name: vmbackup
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /victoria-metrics-data
          mountPropagation: None
          name: data
          readOnly: true
        - mountPath: /scripts
          mountPropagation: None
          name: scripts
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - command:
        - /bin/sh
        - /scripts/restore.sh
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: MINIO_ACCESS_KEY
              name: victoriametrics-s3
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: MINIO_SECRET_KEY
              name: victoriametrics-s3
              optional: false
        image: victoriametrics/vmrestore
        imagePullPolicy: IfNotPresent
        name: vmrestore
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /victoria-metrics-data
          mountPropagation: None
          name: data
        - mountPath: /scripts
          mountPropagation: None
          name: scripts
      nodeSelector:
        kubernetes.io/hostname: hestia
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: victoriametrics
      serviceAccountName: victoriametrics
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 600
      volumes:
      - configMap:
          defaultMode: 420
          name: victoriametrics-config
          optional: false
        name: config
      - configMap:
          defaultMode: 493
          name: victoriametrics-backup-script
          optional: false
        name: scripts
      - name: data
        persistentVolumeClaim:
          claimName: victoriametrics-data
