apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-vaultwarden.yaml
- ingress-default-vaultwarden.yaml
- persistentvolumeclaim-default-vaultwarden-data-sw.yaml
- service-default-vaultwarden.yaml

images:
- name: "vaultwarden/server"
  newTag: "latest"
