apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9100'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: node-exporter
    app.kubernetes.io/name: node-exporter
  name: node-exporter
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: node-exporter
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP
