apiVersion: v1
data:
  cluster.xml: "<clickhouse>\n  <listen_host>0.0.0.0</listen_host>\n  <keeper_server>\n\
    \    <tcp_port>9181</tcp_port>\n    <server_id>1</server_id>\n    <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>\n\
    \    <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>\n\
    \    <coordination_settings>\n      <operation_timeout_ms>10000</operation_timeout_ms>\n\
    \      <session_timeout_ms>30000</session_timeout_ms>\n      <raft_logs_level>warning</raft_logs_level>\n\
    \    </coordination_settings>\n    <raft_configuration>\n      <server>\n    \
    \    <id>1</id>\n        <hostname>localhost</hostname>\n        <port>9444</port>\n\
    \      </server>\n    </raft_configuration>\n  </keeper_server>\n  <zookeeper>\n\
    \    <node>\n      <host>localhost</host>\n      <port>9181</port>\n    </node>\n\
    \  </zookeeper>\n  <remote_servers>\n    <default>\n      <shard>\n        <replica>\n\
    \          <host>localhost</host>\n          <port>9000</port>\n        </replica>\n\
    \      </shard>\n    </default>\n  </remote_servers>\n  <macros>\n    <shard>1</shard>\n\
    \    <replica>clickhouse-1</replica>\n  </macros>\n</clickhouse>\n"
immutable: false
kind: ConfigMap
metadata:
  labels:
    app: clickhouse
  name: clickhouse-config
  namespace: default
