apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-clickhouse-config.yaml
- deployment-default-clickhouse.yaml
- persistentvolumeclaim-default-clickhouse-data.yaml
- service-default-clickhouse.yaml

images:
- name: "clickhouse/clickhouse-server"
  newTag: "26.5-alpine"
