apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- certificate-flux-system-wildcard-brmartin-tls.yaml
- ingress-flux-webhook.yaml
- receiver-cluster-state.yaml
- kustomization-storage-classes.yaml
- kustomization-storage.yaml
- kustomization-storage-access.yaml
- kustomization-storage-backups.yaml
- kustomization-platform.yaml
- kustomization-shared-services.yaml
- kustomization-observability-core.yaml
- kustomization-observability-ui.yaml
- kustomization-apps.yaml

images:
- name: "ghcr.io/fluxcd/source-controller"
  newTag: "v1.8.3"
- name: "ghcr.io/fluxcd/kustomize-controller"
  newTag: "v1.8.4"
- name: "ghcr.io/fluxcd/notification-controller"
  newTag: "v1.8.4"
