apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    arch: amd64
  name: gitlab-runner
spec:
  selector:
    matchLabels:
      arch: amd64
  template:
    metadata:
      labels:
        arch: amd64
    spec:
      initContainers:
      - env:
        - name: RUNNER_NAME
          value: k8s-amd64
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              key: runner_token_amd64
              name: gitlab-runner-secrets
              optional: false
        name: config-generator
      nodeSelector:
        kubernetes.io/arch: amd64
