apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-langfuse-web.yaml
- deployment-default-langfuse-worker.yaml
- ingressroute-default-langfuse.yaml
- service-default-langfuse-web.yaml

images:
- name: "langfuse/langfuse"
  newTag: "3"
- name: "langfuse/langfuse-worker"
  newTag: "3"
