apiVersion: v1
data:
  system_id: r_X8Dk6mQ2LwPs
immutable: false
kind: ConfigMap
metadata:
  labels:
    app: gitlab-runner
    pool: services
  name: gitlab-runner-system-id-services
  namespace: default
