apiVersion: v1
data:
  system_id: r_87qXxf9xnF9v
immutable: false
kind: ConfigMap
metadata:
  labels:
    app: gitlab-runner
    arch: amd64
  name: gitlab-runner-system-id-amd64
  namespace: default
