apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob-default-restic-critical-pvc-backup.yaml
- cronjob-default-restic-repo-maintenance.yaml

configMapGenerator:
- name: restic-backup-scripts
  namespace: default
  files:
  - backup-critical-pvc.sh=files/backup-critical-pvc.sh
  - maintenance.sh=files/maintenance.sh
  - critical-pvc-paths.txt=files/critical-pvc-paths.txt
  - excludes.txt=files/excludes.txt
  - backup-policy.yaml=files/backup-policy.yaml
  options:
    disableNameSuffixHash: true
    labels:
      app: restic-backup

images:
- name: "restic/restic"
  newTag: "0.19.1"
