apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob-default-restic-backup.yaml
- persistentvolume-restic-seaweedfs-filer-root.yaml
- persistentvolumeclaim-default-restic-seaweedfs-filer-root.yaml

configMapGenerator:
- name: restic-backup-scripts
  namespace: default
  files:
  - backup.sh=files/backup.sh
  - excludes.txt=files/excludes.txt
  options:
    disableNameSuffixHash: true
    labels:
      app: restic-backup

images:
- name: "restic/restic"
  newTag: "0.18.1"
