apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-restic-backup-scripts.yaml
- cronjob-default-restic-backup.yaml
- persistentvolume-restic-seaweedfs-filer-root.yaml
- persistentvolumeclaim-default-restic-seaweedfs-filer-root.yaml

images:
- name: "restic/restic"
  newTag: "0.18.1"
