apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/seaweedfs-csi-driver
  labels:
    app: restic-backup
  name: restic-seaweedfs-filer-root
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  csi:
    driver: seaweedfs-csi-driver
    readOnly: true
    volumeHandle: /buckets
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs
  volumeMode: Filesystem
