name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NOMAD_ADDR: "${{ vars.NOMAD_ADDR }}"
  NOMAD_TOKEN: "${{ secrets.NOMAD_TOKEN }}"
  PG_CONN_STR: "${{ secrets.PG_CONN_STR }}"
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  terraform-cicd:
    name: Terraform CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Nomad
        uses: hashicorp/setup-nomad@main

      - name: Create Terraform Plugin Cache Dir
        run: mkdir -v -p $TF_PLUGIN_CACHE_DIR

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Nomad fmt
        run: nomad fmt -recursive -check

      - name: Cache Terraform Plugin Dir
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-plugins-

      - name: Cache TFLint Dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v6
      - run: |
          tflint --init
          tflint

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      - name: Validate Nomad Jobs from Plan
        if: github.event_name == 'pull_request'
        run: |
          # Extract and validate jobspecs from plan
          terraform show -json tfplan | jq -c '.resource_changes[] | select(.type == "nomad_job") | {address, jobspec: .change.after.jobspec, hcl2: .change.after.hcl2}' | while read -r job; do
            address=$(echo "$job" | jq -r '.address')
            jobspec=$(echo "$job" | jq -r '.jobspec')
            hcl2_vars=$(echo "$job" | jq -r '.hcl2[0].vars // empty')
            
            echo "Validating $address..."
            
            # Write jobspec to temp file
            tmpfile=$(mktemp)
            echo "$jobspec" > "$tmpfile"
            
            # Build var args if HCL2 vars exist
            var_args=""
            if [ -n "$hcl2_vars" ] && [ "$hcl2_vars" != "null" ]; then
              while IFS= read -r key; do
                value=$(echo "$hcl2_vars" | jq -r ".$key")
                var_args="$var_args -var=$key=$value"
              done < <(echo "$hcl2_vars" | jq -r 'keys[]')
            fi
            
            # Validate with vars if present
            if [ -n "$var_args" ]; then
              nomad job validate $var_args "$tmpfile" || exit 1
            else
              nomad job validate "$tmpfile" || exit 1
            fi
            
            rm -f "$tmpfile"
          done

      - name: Terraform Plan (for main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform plan -out=tfplan

      - name: Validate Nomad Jobs from Plan (for main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Extract and validate jobspecs from plan
          terraform show -json tfplan | jq -c '.resource_changes[] | select(.type == "nomad_job") | {address, jobspec: .change.after.jobspec, hcl2: .change.after.hcl2}' | while read -r job; do
            address=$(echo "$job" | jq -r '.address')
            jobspec=$(echo "$job" | jq -r '.jobspec')
            hcl2_vars=$(echo "$job" | jq -r '.hcl2[0].vars // empty')
            
            echo "Validating $address..."
            
            # Write jobspec to temp file
            tmpfile=$(mktemp)
            echo "$jobspec" > "$tmpfile"
            
            # Build var args if HCL2 vars exist
            var_args=""
            if [ -n "$hcl2_vars" ] && [ "$hcl2_vars" != "null" ]; then
              while IFS= read -r key; do
                value=$(echo "$hcl2_vars" | jq -r ".$key")
                var_args="$var_args -var=$key=$value"
              done < <(echo "$hcl2_vars" | jq -r 'keys[]')
            fi
            
            # Validate with vars if present
            if [ -n "$var_args" ]; then
              nomad job validate $var_args "$tmpfile" || exit 1
            else
              nomad job validate "$tmpfile" || exit 1
            fi
            
            rm -f "$tmpfile"
          done

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply tfplan
