name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NOMAD_ADDR: "${{ vars.NOMAD_ADDR }}"
  NOMAD_TOKEN: "${{ secrets.NOMAD_TOKEN }}"
  PG_CONN_STR: "${{ secrets.PG_CONN_STR }}"
  TF_CLI_ARGS: "-no-color"
  TF_IN_AUTOMATION: true
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  terraform-cicd:
    name: Terraform CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Nomad
        uses: hashicorp/setup-nomad@main

      - name: Create Terraform Plugin Cache Dir
        run: mkdir -v -p $TF_PLUGIN_CACHE_DIR

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Nomad fmt
        run: nomad fmt -recursive -check

      - name: Cache Terraform Plugin Dir
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-plugins-

      - name: Cache TFLint Dir
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v6
      - run: |
          tflint --init
          tflint

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      - name: Validate Nomad Jobs from Plan
        if: github.event_name == 'pull_request'
        run: |
          # Extract and validate jobspecs from plan
          mkdir -p /tmp/jobspecs
          
          terraform show -json tfplan | jq -r '
            .planned_values.root_module.child_modules[]? |
            select(.resources[]?.type == "nomad_job") |
            .resources[] |
            select(.type == "nomad_job") |
            "\(.address)\n\(.values.jobspec)\n---JOBSPEC_END---"
          ' | {
            while IFS= read -r address; do
              # Read until we hit the delimiter
              jobspec=""
              while IFS= read -r line; do
                if [ "$line" = "---JOBSPEC_END---" ]; then
                  break
                fi
                jobspec="${jobspec}${line}\n"
              done
              
              if [ -n "$jobspec" ] && [ "$jobspec" != "null" ]; then
                echo "Validating $address..."
                printf "%b" "$jobspec" | nomad job validate - || exit 1
              fi
            done
          }

      - name: Terraform Plan (for main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform plan -out=tfplan

      - name: Validate Nomad Jobs from Plan (for main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Extract and validate jobspecs from plan
          mkdir -p /tmp/jobspecs
          
          terraform show -json tfplan | jq -r '
            .planned_values.root_module.child_modules[]? |
            select(.resources[]?.type == "nomad_job") |
            .resources[] |
            select(.type == "nomad_job") |
            "\(.address)\n\(.values.jobspec)\n---JOBSPEC_END---"
          ' | {
            while IFS= read -r address; do
              # Read until we hit the delimiter
              jobspec=""
              while IFS= read -r line; do
                if [ "$line" = "---JOBSPEC_END---" ]; then
                  break
                fi
                jobspec="${jobspec}${line}\n"
              done
              
              if [ -n "$jobspec" ] && [ "$jobspec" != "null" ]; then
                echo "Validating $address..."
                printf "%b" "$jobspec" | nomad job validate - || exit 1
              fi
            done
          }

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply tfplan
