name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  TF_IN_AUTOMATION: true

jobs:
  lint:
    runs-on: ubuntu-latest-slim
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Nomad
        uses: hashicorp/setup-nomad@main

      - name: Terraform fmt
        run: terraform fmt -recursive -check

      - name: Nomad fmt
        run: nomad fmt -recursive -check
