apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-nextcloud-config-override.yaml
- deployment-default-nextcloud.yaml
- ingressroute-default-nextcloud.yaml
- middleware-default-nextcloud-webdav-redirect.yaml
- service-default-nextcloud.yaml

images:
- name: "redis"
  newTag: "8-alpine"
- name: "nextcloud"
  newTag: "33.0.5"
- name: "busybox"
  newTag: "1"
