apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: seaweedfs
    component: consumer-recycler
    environment: prod
  name: seaweedfs-consumer-recycler
  namespace: default
