apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
  labels:
    app: seaweedfs
    component: consumer-recycler
    environment: prod
  name: seaweedfs-consumer-recycler-metrics
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app: seaweedfs
    app.kubernetes.io/name: seaweedfs-consumer-recycler
  sessionAffinity: None
  type: ClusterIP
