apiVersion: v1
kind: Secret
metadata:
  name: storage-reader-token
  namespace: hermes-observer
  annotations:
    kubernetes.io/service-account.name: storage-reader
type: kubernetes.io/service-account-token
