apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-reader
  namespace: hermes-observer
  labels:
    app.kubernetes.io/name: hermes-observer
    app.kubernetes.io/part-of: hermes
automountServiceAccountToken: false
