apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-workspace-windsor
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: hermes-workspace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: windsor-nfs-rwx
  volumeMode: Filesystem
