schemaVersion: 1
artifact:
  repository: registry.brmartin.co.uk:443/autonomous-investing/system/ib-gateway
  digest: sha256:71ea9b027ac9da3ca9e7b94b6e6bc04b1fc1bcdc42687d1a6231cf2239bf707e
  reference: registry.brmartin.co.uk:443/autonomous-investing/system/ib-gateway@sha256:71ea9b027ac9da3ca9e7b94b6e6bc04b1fc1bcdc42687d1a6231cf2239bf707e
provenance:
  systemProjectId: 35
  protectedMainPipelineId: 5261
  admissionJobId: 19838
  sourceCommit: 4a9a2c858fa23e182e06b5cd835b9dddb6dc789d
