apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
  namespace: kube-system
spec:
  clusterIP: 10.43.112.194
  clusterIPs:
    - 10.43.112.194
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8000
  selector:
    app: vpa-admission-controller
  sessionAffinity: None
  type: ClusterIP
