apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
  ports:
  - name: grpc
    port: 7233
    targetPort: rpc
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend-headless
  namespace: temporal
  annotations: {prometheus.io/scrape: "true", prometheus.io/port: "9090"}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {app.kubernetes.io/name: temporal, app.kubernetes.io/component: frontend}
  ports:
  - {name: rpc, port: 7233, targetPort: rpc}
  - {name: membership, port: 6933, targetPort: membership}
  - {name: metrics, port: 9090, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-history-headless
  namespace: temporal
  annotations: {prometheus.io/scrape: "true", prometheus.io/port: "9090"}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {app.kubernetes.io/name: temporal, app.kubernetes.io/component: history}
  ports:
  - {name: rpc, port: 7234, targetPort: rpc}
  - {name: membership, port: 6934, targetPort: membership}
  - {name: metrics, port: 9090, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-matching-headless
  namespace: temporal
  annotations: {prometheus.io/scrape: "true", prometheus.io/port: "9090"}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {app.kubernetes.io/name: temporal, app.kubernetes.io/component: matching}
  ports:
  - {name: rpc, port: 7235, targetPort: rpc}
  - {name: membership, port: 6935, targetPort: membership}
  - {name: metrics, port: 9090, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-worker-headless
  namespace: temporal
  annotations: {prometheus.io/scrape: "true", prometheus.io/port: "9090"}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {app.kubernetes.io/name: temporal, app.kubernetes.io/component: worker}
  ports:
  - {name: membership, port: 6939, targetPort: membership}
  - {name: metrics, port: 9090, targetPort: metrics}
