apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: gitlab-agent
    app.kubernetes.io/name: gitlab-agent
  name: gitlab-agent-leases
  namespace: gitlab-agent
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
