apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: gitlab-agent
    app.kubernetes.io/name: gitlab-agent
  name: gitlab-agent-events
  namespace: gitlab-agent
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
