apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gitlab-agent
    app.kubernetes.io/name: gitlab-agent
  name: gitlab-agent
  namespace: gitlab-agent
automountServiceAccountToken: false
