apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ciliumnetworkpolicy-default-lldap.yaml
- configmap-default-lldap-config.yaml
- deployment-default-lldap.yaml
- ingress-default-lldap.yaml
- service-default-lldap.yaml

images:
- name: "lldap/lldap"
  newTag: "stable"
