apiVersion: v1
data:
  config.yml: "version: 0.1\nlog:\n  level: warn\n  formatter: json\nstorage:\n  filesystem:\n\
    \    rootdirectory: /var/lib/registry\n  delete:\n    enabled: true\n  cache:\n\
    \    blobdescriptor: inmemory\nhttp:\n  addr: 0.0.0.0:5000\n  headers:\n    X-Content-Type-Options:\
    \ [nosniff]\nhealth:\n  storagedriver:\n    enabled: true\n    interval: 10s\n\
    \    threshold: 3\nauth:\n  token:\n    realm: https://git.brmartin.co.uk/jwt/auth\n\
    \    service: container_registry\n    issuer: gitlab-issuer\n    rootcertbundle:\
    \ /etc/docker/registry/certs/gitlab-registry.crt\n"
immutable: false
kind: ConfigMap
metadata:
  labels:
    app: gitlab
  name: gitlab-registry-config
  namespace: default
