apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: gitlab
    component: kas
  name: gitlab-kas-config
  namespace: default
data:
  config.yaml: |
    agent:
      listen:
        address: ":8150"
        websocket: true
      kubernetes_api:
        listen:
          address: ":8154"
        url_path_prefix: "/-/kubernetes-agent/k8s-proxy"
        websocket_token_secret_file: /etc/kas/.gitlab_kas_websocket_token_secret
    gitlab:
      address: http://gitlab-workhorse:8181
      external_url: https://git.brmartin.co.uk
      authentication_secret_file: /etc/kas/.gitlab_kas_secret
    observability:
      listen:
        address: ":8151"
      liveness_probe:
        url_path: /liveness
      readiness_probe:
        url_path: /readiness
    redis:
      database_index: 3
      server:
        address: gitlab-redis:6379
    api:
      listen:
        address: ":8153"
        authentication_secret_file: /etc/kas/.gitlab_kas_secret
    private_api:
      listen:
        address: ":8155"
        authentication_secret_file: /etc/kas/.gitlab_kas_private_api_secret
