apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-migrations-version-run
  namespace: default
  labels:
    app: gitlab
    component: migrations
    gitlab.com/rails-registry-auth: "true"
    gitlab.com/rails-runtime: "true"
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        elastic.co/dataset: kubernetes.container_logs.gitlab
      labels:
        app: gitlab
        component: migrations
    spec:
      automountServiceAccountToken: true
      containers:
      - name: migrations
        image: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ce:placeholder
        imagePullPolicy: IfNotPresent
        args:
        - /scripts/db-migrate
        env:
        - name: CONFIG_TEMPLATE_DIRECTORY
          value: /var/opt/gitlab/config/templates
        - name: CONFIG_DIRECTORY
          value: /srv/gitlab/config
        - name: GITLAB_HOST
          value: git.brmartin.co.uk
        - name: GITLAB_PORT
          value: '443'
        - name: GITLAB_HTTPS
          value: 'true'
        - name: ENABLE_BOOTSNAP
          value: '1'
        - name: ACTION_CABLE_IN_APP
          value: 'true'
        - name: GITALY_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: gitlab-gitaly
              optional: false
        - name: GITLAB_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: SMTP_USERNAME
              name: gitlab-smtp-secret
              optional: false
        - name: GITLAB_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SMTP_PASSWORD
              name: gitlab-smtp-secret
              optional: false
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 75m
            memory: 2100Mi
        volumeMounts:
        - mountPath: /srv/gitlab/public/uploads
          mountPropagation: HostToContainer
          name: uploads
        - mountPath: /srv/gitlab/shared
          mountPropagation: HostToContainer
          name: shared
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: false
        runAsUser: 1000
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: gitlab-uploads-sw
      - name: shared
        persistentVolumeClaim:
          claimName: gitlab-shared-sw
