apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-gitaly-config.yaml
- configmap-default-gitlab-config-templates.yaml
- configmap-default-gitlab-registry-config.yaml
- configmap-default-gitlab-smtp-config.yaml
- configmap-default-workhorse-config.yaml
- deployment-default-gitlab-gitaly.yaml
- deployment-default-gitlab-redis.yaml
- deployment-default-gitlab-registry.yaml
- deployment-default-gitlab-sidekiq.yaml
- deployment-default-gitlab-webservice.yaml
- deployment-default-gitlab-workhorse.yaml
- ingressroute-default-gitlab.yaml
- ingressroute-default-gitlab-registry.yaml
- persistentvolumeclaim-default-gitlab-registry-sw.yaml
- persistentvolumeclaim-default-gitlab-repositories-sw.yaml
- persistentvolumeclaim-default-gitlab-shared-sw.yaml
- persistentvolumeclaim-default-gitlab-uploads-sw.yaml
- service-default-gitlab-gitaly.yaml
- service-default-gitlab-redis.yaml
- service-default-gitlab-registry.yaml
- service-default-gitlab-registry-internal.yaml
- service-default-gitlab-webservice.yaml
- service-default-gitlab-workhorse.yaml
