apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    arch: any
  name: gitlab-runner
spec:
  selector:
    matchLabels:
      arch: any
  template:
    metadata:
      labels:
        arch: any
