apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-athenaeum-frontend-config.yaml
- deployment-default-athenaeum-backend.yaml
- deployment-default-athenaeum-frontend.yaml
- deployment-default-athenaeum-redis.yaml
- ingress-default-athenaeum.yaml
- service-default-athenaeum-backend.yaml
- service-default-athenaeum-frontend.yaml
- service-default-athenaeum-redis.yaml

images:
- name: "registry.brmartin.co.uk/ben/athenaeum/backend"
  newTag: "5d0414d5"
- name: "registry.brmartin.co.uk/ben/athenaeum/frontend"
  newTag: "5d0414d5"
- name: "redis"
  newTag: "8-alpine"
