apiVersion: v1
data:
  loki.yaml: |
    auth_enabled: false
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    compactor:
      compaction_interval: 10m
      delete_request_store: s3
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      retention_enabled: true
      working_directory: /loki/compactor
    ingester:
      wal:
        dir: /loki/wal
        enabled: true
        flush_on_shutdown: true
    limits_config:
      retention_period: 720h
    schema_config:
      configs:
        - from: "2024-01-01"
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v13
          store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        access_key_id: "__LOKI_ACCESS_KEY_ID__"
        bucketnames: "__LOKI_BUCKET__"
        endpoint: "__LOKI_ENDPOINT__"
        insecure: true
        region: "__LOKI_REGION__"
        s3forcepathstyle: true
        secret_access_key: "__LOKI_SECRET_ACCESS_KEY__"
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
immutable: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  name: loki-config
  namespace: default
