apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-loki-config.yaml
- persistentvolumeclaim-default-data-loki-0.yaml
- service-default-loki.yaml
- statefulset-default-loki.yaml

images:
- name: "grafana/loki"
  newTag: "3.7.2"
