apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/selected-node: hestia
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  name: data-loki-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-retain
  volumeMode: Filesystem
