apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  labels:
    app: plex
    environment: prod
  name: plex-backup
bucketClaim:
  name: plex-backup
  namespace: default
bucketClassName: seaweedfs
deletionPolicy: Retain
driverName: seaweedfs.objectstorage.k8s.io
existingBucketID: plex-backup
protocols:
  - s3
