apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  labels:
    app: victoriametrics
    environment: prod
  name: victoriametrics
  namespace: default
spec:
  bucketClassName: seaweedfs
  existingBucketName: victoriametrics
  protocols:
    - s3
