apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  labels:
    app: langfuse
    environment: prod
  name: langfuse
  namespace: default
spec:
  bucketClassName: seaweedfs
  existingBucketName: langfuse
  protocols:
    - s3
