apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccess
metadata:
  labels:
    app: loki
    environment: prod
  name: loki
  namespace: default
spec:
  bucketAccessClassName: seaweedfs-readwrite
  bucketClaimName: loki
  credentialsSecretName: loki-cosi-s3
  protocol: s3
