apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccess
metadata:
  labels:
    app: langfuse
    environment: prod
  name: langfuse
  namespace: default
spec:
  bucketAccessClassName: seaweedfs-readwrite
  bucketClaimName: langfuse
  credentialsSecretName: langfuse-s3
  protocol: s3
