apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  labels:
    app: seerr
    environment: prod
    migration-role: active-backup
  name: seerr-litestream
spec:
  bucketClaim:
    name: seerr-litestream
    namespace: default
  bucketClassName: seaweedfs
  deletionPolicy: Retain
  driverName: seaweedfs.objectstorage.k8s.io
  existingBucketID: seerr-litestream
  protocols:
    - s3
