apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceaccount-container-object-storage-system-seaweedfs-cosi-driver.yaml
- clusterrole-seaweedfs-cosi-driver.yaml
- clusterrolebinding-seaweedfs-cosi-driver.yaml
- role-container-object-storage-system-seaweedfs-cosi-driver.yaml
- rolebinding-container-object-storage-system-seaweedfs-cosi-driver.yaml
- deployment-container-object-storage-system-seaweedfs-cosi-driver.yaml
- bucketclass-seaweedfs.yaml
- bucketaccessclass-seaweedfs-readwrite.yaml
- bucketaccessclass-seaweedfs-readonly.yaml
- bucket-plex-backup.yaml
- bucketclaim-default-plex-backup.yaml
- bucketaccess-default-plex-backup.yaml
- bucket-victoriametrics.yaml
- bucketclaim-default-victoriametrics.yaml
- bucketaccess-default-victoriametrics.yaml
- bucket-loki.yaml
- bucketclaim-default-loki.yaml
- bucketaccess-default-loki.yaml
- bucket-athenaeum-attachments.yaml
- bucketclaim-default-athenaeum-attachments.yaml
- bucketaccess-default-athenaeum-attachments.yaml
- bucket-gitlab-runner-cache.yaml
- bucketclaim-default-gitlab-runner-cache.yaml
- bucketaccess-default-gitlab-runner-cache.yaml
- bucket-renovate-cache.yaml
- bucketclaim-default-renovate-cache.yaml
- bucketaccess-default-renovate-cache.yaml

images:
- name: "registry.brmartin.co.uk/ben/cluster-state/seaweedfs-cosi-driver"
  newTag: "latest"
- name: "registry.brmartin.co.uk/ben/cluster-state/cosi-provisioner-sidecar"
  newTag: "latest"
