apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: seaweedfs-cosi-driver
    app.kubernetes.io/name: seaweedfs-cosi-driver
    app.kubernetes.io/part-of: seaweedfs
    environment: prod
  name: seaweedfs-cosi-driver
  namespace: container-object-storage-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seaweedfs-cosi-driver
subjects:
- kind: ServiceAccount
  name: seaweedfs-cosi-driver
  namespace: container-object-storage-system
