apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: seaweedfs-cosi-driver
    app.kubernetes.io/name: seaweedfs-cosi-driver
    app.kubernetes.io/part-of: seaweedfs
    environment: prod
  name: seaweedfs-cosi-driver
  namespace: container-object-storage-system
