apiVersion: v1
data:
  config: "\"apiVersion\": \"v1\"\n\"clusters\":\n- \"cluster\":\n    \"certificate-authority\"\
    : \"/var/run/secrets/kubernetes.io/serviceaccount/ca.crt\"\n    \"server\": \"\
    https://kubernetes.default.svc\"\n  \"name\": \"in-cluster\"\n\"contexts\":\n\
    - \"context\":\n    \"cluster\": \"in-cluster\"\n    \"user\": \"headlamp\"\n\
    \  \"name\": \"service-account\"\n\"current-context\": \"service-account\"\n\"\
    kind\": \"Config\"\n\"users\":\n- \"name\": \"headlamp\"\n  \"user\":\n    \"\
    tokenFile\": \"/var/run/secrets/kubernetes.io/serviceaccount/token\"\n"
immutable: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/name: headlamp
  name: headlamp-kubeconfig
  namespace: kube-system
