apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding-headlamp.yaml
- configmap-kube-system-headlamp-kubeconfig.yaml
- deployment-kube-system-headlamp.yaml
- ingressroute-kube-system-headlamp.yaml
- service-kube-system-headlamp.yaml
- serviceaccount-kube-system-headlamp.yaml

images:
- name: "ghcr.io/headlamp-k8s/headlamp"
  newTag: "v0.43.0"
