apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-glitchtip.yaml
- ingress-default-glitchtip.yaml
- persistentvolumeclaim-default-glitchtip-uploads.yaml
- service-default-glitchtip.yaml

images:
- name: "glitchtip/glitchtip"
  newTag: "6.1.5"
