apiVersion: 1
contactPoints:
- name: email
  orgId: 1
  receivers:
  - settings:
      addresses: ${GF_ALERT_EMAIL_TO}
    type: email
    uid: email-alerts
- name: hermes-notify-only
  orgId: 1
  receivers:
  - disableResolveMessage: true
    settings:
      hmacConfig:
        header: X-Webhook-Signature
        secret: ${GF_HERMES_WEBHOOK_HMAC_SECRET}
      httpMethod: POST
      maxAlerts: '10'
      url: http://hermes-webhook.default.svc.cluster.local:8644/webhooks/grafana-notify-only
    type: webhook
    uid: hermes-notify-only-alerts
- name: hermes-actionable
  orgId: 1
  receivers:
  - disableResolveMessage: true
    settings:
      hmacConfig:
        header: X-Webhook-Signature
        secret: ${GF_HERMES_WEBHOOK_HMAC_SECRET}
      httpMethod: POST
      maxAlerts: '10'
      url: http://hermes-webhook.default.svc.cluster.local:8644/webhooks/grafana-actionable-alerts
    type: webhook
    uid: hermes-actionable-alerts
- name: email-and-hermes-actionable
  orgId: 1
  receivers:
  - settings:
      addresses: ${GF_ALERT_EMAIL_TO}
    type: email
    uid: email-hermes-act-email
  - disableResolveMessage: true
    settings:
      hmacConfig:
        header: X-Webhook-Signature
        secret: ${GF_HERMES_WEBHOOK_HMAC_SECRET}
      httpMethod: POST
      maxAlerts: '10'
      url: http://hermes-webhook.default.svc.cluster.local:8644/webhooks/grafana-actionable-alerts
    type: webhook
    uid: email-hermes-act-webhook
