apiVersion: 1
contactPoints:
- name: email
  orgId: 1
  receivers:
  - settings:
      addresses: ${GF_ALERT_EMAIL_TO}
    type: email
    uid: email-alerts
- name: hermes
  orgId: 1
  receivers:
  - disableResolveMessage: false
    settings:
      hmacConfig:
        header: X-Webhook-Signature
        secret: ${GF_HERMES_WEBHOOK_HMAC_SECRET}
      httpMethod: POST
      maxAlerts: '10'
      url: http://hermes-webhook.default.svc.cluster.local:8644/webhooks/grafana-alerts
    type: webhook
    uid: hermes-alerts
- name: email-and-hermes
  orgId: 1
  receivers:
  - settings:
      addresses: ${GF_ALERT_EMAIL_TO}
    type: email
    uid: email-and-hermes-email-alerts
  - disableResolveMessage: false
    settings:
      hmacConfig:
        header: X-Webhook-Signature
        secret: ${GF_HERMES_WEBHOOK_HMAC_SECRET}
      httpMethod: POST
      maxAlerts: '10'
      url: http://hermes-webhook.default.svc.cluster.local:8644/webhooks/grafana-alerts
    type: webhook
    uid: email-and-hermes-webhook-alerts
