apiVersion: v1
data:
  client: '{"m.homeserver":{"base_url":"https://matrix.brmartin.co.uk"},"org.matrix.msc2965.authentication":{"account":"https://mas.brmartin.co.uk/account","issuer":"https://mas.brmartin.co.uk/"},"org.matrix.msc3575.proxy":{"url":"https://matrix.brmartin.co.uk"}}'
  nginx.conf: "user  nginx;\nworker_processes  auto;\n\nerror_log  stderr;\npid  \
    \      /var/run/nginx.pid;\n\nevents {\n  worker_connections  1024;\n}\n\nhttp\
    \ {\n  include            /etc/nginx/mime.types;\n  default_type       application/octet-stream;\n\
    \  access_log         off;\n  http2              on;\n  proxy_buffering    off;\n\
    \  sendfile           on;\n  keepalive_timeout  65;\n\n  server {\n    listen\
    \  8080;\n\n    location / {\n      return  404;\n    }\n\n    location /health\
    \ {\n      return        200 \"OK\";\n      default_type  text/plain;\n    }\n\
    \n    location /.well-known/matrix {\n      root          /usr/share/nginx/html;\n\
    \      add_header    Access-Control-Allow-Origin *;\n    }\n  }\n}\n"
  server: '{"m.server":"matrix.brmartin.co.uk:443"}'
immutable: false
kind: ConfigMap
metadata:
  name: matrix-nginx-config
  namespace: default
