apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-default-cinny-config.yaml
- configmap-default-element-config.yaml
- configmap-default-mas-config-template.yaml
- configmap-default-matrix-nginx-config.yaml
- configmap-default-synapse-config.yaml
- deployment-default-cinny.yaml
- deployment-default-element.yaml
- deployment-default-element-admin.yaml
- deployment-default-mas.yaml
- deployment-default-matrix-nginx.yaml
- deployment-default-synapse.yaml
- deployment-default-whatsapp-bridge.yaml
- ingressroute-default-cinny.yaml
- ingressroute-default-element.yaml
- ingressroute-default-element-admin.yaml
- ingressroute-default-mas.yaml
- ingressroute-default-matrix-wellknown.yaml
- ingressroute-default-synapse.yaml
- middleware-default-mas-cors.yaml
- middleware-default-synapse-buffering.yaml
- middleware-default-synapse-headers.yaml
- middleware-default-wellknown-cors.yaml
- persistentvolumeclaim-default-matrix-config-sw.yaml
- persistentvolumeclaim-default-matrix-media-store-sw.yaml
- persistentvolumeclaim-default-matrix-synapse-data-sw.yaml
- persistentvolumeclaim-default-matrix-whatsapp-data-sw.yaml
- service-default-cinny.yaml
- service-default-element.yaml
- service-default-element-admin.yaml
- service-default-mas.yaml
- service-default-matrix-nginx.yaml
- service-default-synapse.yaml
- service-default-whatsapp-bridge.yaml

images:
- name: "ghcr.io/cinnyapp/cinny"
  newTag: "v4.12.3"
- name: "docker.io/vectorim/element-web"
  newTag: "v1.12.21"
- name: "oci.element.io/element-admin"
  newTag: "latest"
- name: "ghcr.io/element-hq/matrix-authentication-service"
  newTag: "1.19.0"
- name: "busybox"
  newTag: "1.38"
- name: "docker.io/library/nginx"
  newTag: "1.31.2-alpine"
- name: "ghcr.io/element-hq/synapse"
  newTag: "v1.155.0"
- name: "dock.mau.dev/mautrix/whatsapp"
  newTag: "v0.2606.0"
