[runners.cache]
  Type = "s3"
  Shared = true
  [runners.cache.s3]
    ServerAddress = "seaweedfs-s3.default.svc.cluster.local:8333"
    BucketName = "gitlab-runner-cache"
    Insecure = true
    AuthenticationType = "access-key"
    AccessKey = "MINIO_ACCESS_KEY_PLACEHOLDER"
    SecretKey = "MINIO_SECRET_KEY_PLACEHOLDER"
