[runners.cache]
  Type = "s3"
  Shared = true
  [runners.cache.s3]
    ServerAddress = "S3_SERVER_ADDRESS_PLACEHOLDER"
    BucketName = "S3_BUCKET_NAME_PLACEHOLDER"
    Insecure = true
    AuthenticationType = "access-key"
    AccessKey = "MINIO_ACCESS_KEY_PLACEHOLDER"
    SecretKey = "MINIO_SECRET_KEY_PLACEHOLDER"
