apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- configmap-default-gitlab-runner-registries-conf.yaml
- role-default-gitlab-runner.yaml
- rolebinding-default-gitlab-runner.yaml
- serviceaccount-default-gitlab-runner.yaml
