apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
data:
  enable-node-selector-labels: "true"
  node-labels: kubernetes.io/hostname
