apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-default-open-webui.yaml
- ingressroute-default-open-webui.yaml
- persistentvolumeclaim-default-open-webui-data-sw.yaml
- service-default-open-webui.yaml

images:
- name: "ghcr.io/open-webui/open-webui"
  newTag: "v0.9.2"
