apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-seaweedfs-consumer-recycler.yaml
- clusterrole-seaweedfs-csi-attacher.yaml
- clusterrole-seaweedfs-csi-node.yaml
- clusterrole-seaweedfs-csi-provisioner.yaml
- clusterrole-seaweedfs-csi-resizer.yaml
- clusterrolebinding-seaweedfs-consumer-recycler.yaml
- clusterrolebinding-seaweedfs-csi-attacher.yaml
- clusterrolebinding-seaweedfs-csi-node.yaml
- clusterrolebinding-seaweedfs-csi-provisioner.yaml
- clusterrolebinding-seaweedfs-csi-resizer.yaml
- daemonset-default-seaweedfs-consumer-recycler.yaml
- daemonset-default-seaweedfs-csi-node.yaml
- daemonset-default-seaweedfs-mount.yaml
- daemonset-default-seaweedfs-volume.yaml
- deployment-default-seaweedfs-csi-controller.yaml
- deployment-default-seaweedfs-s3.yaml
- role-default-seaweedfs-csi-leader-election.yaml
- rolebinding-default-seaweedfs-csi-leader-election.yaml
- service-default-seaweedfs-consumer-recycler-metrics.yaml
- service-default-seaweedfs-filer.yaml
- service-default-seaweedfs-master.yaml
- service-default-seaweedfs-s3.yaml
- service-default-seaweedfs-volume.yaml
- serviceaccount-default-seaweedfs-consumer-recycler.yaml
- serviceaccount-default-seaweedfs-csi.yaml
- statefulset-default-seaweedfs-filer.yaml
- statefulset-default-seaweedfs-master.yaml
