apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-seaweedfs-consumer-recycler.yaml
- clusterrole-seaweedfs-csi-attacher.yaml
- clusterrole-seaweedfs-csi-node.yaml
- clusterrole-seaweedfs-csi-provisioner.yaml
- clusterrole-seaweedfs-csi-resizer.yaml
- clusterrolebinding-seaweedfs-consumer-recycler.yaml
- clusterrolebinding-seaweedfs-csi-attacher.yaml
- clusterrolebinding-seaweedfs-csi-node.yaml
- clusterrolebinding-seaweedfs-csi-provisioner.yaml
- clusterrolebinding-seaweedfs-csi-resizer.yaml
- configmap-default-seaweedfs-filer-config.yaml
- daemonset-default-seaweedfs-consumer-recycler.yaml
- daemonset-default-seaweedfs-csi-node.yaml
- daemonset-default-seaweedfs-mount.yaml
- daemonset-default-seaweedfs-volume.yaml
- deployment-default-seaweedfs-csi-controller.yaml
- deployment-default-seaweedfs-s3.yaml
- role-default-seaweedfs-csi-leader-election.yaml
- rolebinding-default-seaweedfs-csi-leader-election.yaml
- service-default-seaweedfs-consumer-recycler-metrics.yaml
- service-default-seaweedfs-filer.yaml
- service-default-seaweedfs-master.yaml
- service-default-seaweedfs-s3.yaml
- service-default-seaweedfs-volume.yaml
- serviceaccount-default-seaweedfs-consumer-recycler.yaml
- serviceaccount-default-seaweedfs-csi.yaml
- statefulset-default-seaweedfs-filer.yaml
- statefulset-default-seaweedfs-master.yaml

images:
- name: "registry.brmartin.co.uk/ben/seaweedfs-consumer-recycler"
  newTag: "v0.1.28"
- name: "registry.brmartin.co.uk/ben/seaweedfs-csi-driver"
  newTag: "v0.1.28"
- name: "registry.k8s.io/sig-storage/csi-node-driver-registrar"
  newTag: "v2.17.0"
- name: "registry.k8s.io/sig-storage/livenessprobe"
  newTag: "v2.19.0"
- name: "registry.brmartin.co.uk/ben/seaweedfs-mount"
  newTag: "v0.1.37"
- name: "chrislusf/seaweedfs"
  newTag: "4.19-nebm-f0f13507"
- name: "registry.k8s.io/sig-storage/csi-provisioner"
  newTag: "v6.3.0"
- name: "registry.k8s.io/sig-storage/csi-attacher"
  newTag: "v4.12.0"
- name: "registry.k8s.io/sig-storage/csi-resizer"
  newTag: "v2.2.0"
